### PR TITLE
Unprocessed context data is now sent to Rollbar when exceptions are logged

### LINKED ISSUE #36: Context should be included with exceptions
RollbarLogHandler doesn't pass context data when reporting an exception.

### PR DESCRIPTION
**Pull request by charles-rumley**
Fixes #36

### CODE REVIEW

**Comment by jenssegers** [comment]
Are you sure this works, I've been looking at the `report_exception` method in the original Rollbar client and it looks like it should be the third parameter rather than the second.

**Comment by jenssegers** [comment]
But then again, the second parameter for report_message is also $extra_data ...

**Comment by charles-rumley** [comment]
Hmm.. good call, `report_exception` and `report_message` handle `$extra_data` differently. Since information in `$payload_data` is merged and included, we could add context there, but I'm not sure if Rollbar expects arbitrary data in `$payload_data`. I'll give this a more thorough look and update the PR accordingly.

**Comment by jenssegers** [comment]
Great, thanks!

**Comment by charles-rumley** [comment]
As pointed out by @jenssegers and verified by further tests, `$context` should be passed as `$payload_data` rather than `$extra_data`.

**Pull request closed without merging**
