### PR TITLE
use specified rollbar person_fn function

### PR DESCRIPTION
**Pull request by jnbn**
You can now assign and use person_fn from config file and use any user-defined helper function to pass person data to rollbar object.

```
'rollbar' => array(
	    'access_token' => 'XXX',
	    'person_fn' => 'get_rollbar_user',
	    'level' => 'debug'
	),
```

```php
function get_rollbar_user() {
    if (Auth::check()) {
        $user = Auth::user();
        return array(
            'id' => $user->id, // required - value is a string
            'username' => $user->fullName(), // required - value is a string
            'email' => $user->email, // optional - value is a string
        );
    }
    return null;
}
```

### CODE REVIEW

**Comment by jenssegers** [comment]
Before calling the function, you should check if the function exists.

**Comment by jnbn** [comment]
@jenssegers Is everything ok? :)

**Comment by jnbn** [comment]
anything else?

**Comment by jenssegers** [comment]
Why did you change the `resolved` to `isset`?

**Comment by jnbn** [comment]
It was from https://github.com/jenssegers/laravel-rollbar/commit/063f9c317ab0314a457dbd19bf4ed81deee1d8d1

**Pull request closed without merging**
